[package]
name = "web-backend"
version = "0.1.0"
edition = "2021"
description = "Backend functionalities for the cloud service"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
